/**
 * Generates supabase/003_seed_cyprus_dolomites.sql from the data already in
 * index.html.
 *
 * The point of doing this with a script rather than by hand: EVENTS, BOOKINGS,
 * BUDGET and PACKING are the real trip content, and retyping 24 events and 13
 * bookings into SQL is exactly how a wrong date gets baked in silently. This
 * evaluates the actual literals from the shipped file.
 *
 *   node scripts/generate-seed.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(root, 'index.html'), 'utf8');

/** Pull `const NAME = <literal>;` out of the page and evaluate just that. */
function literal(name) {
  const re = new RegExp(`const ${name}\\s*=\\s*([\\[{][\\s\\S]*?)\\n\\s*\\];?|const ${name}\\s*=\\s*([\\[{][\\s\\S]*?)\\n\\s*\\};?`, 'm');
  const m = html.match(re);
  if (!m) throw new Error(`could not find ${name} in index.html`);
  const body = (m[1] !== undefined ? m[1] + '\n]' : m[2] + '\n}');
  return eval('(' + body + ')');
}

const EVENTS   = literal('EVENTS');
const BOOKINGS = literal('BOOKINGS');
const BUDGET   = literal('BUDGET');
const PACKING  = literal('PACKING');
const PEOPLE   = eval('(' + html.match(/const PEOPLE\s*=\s*(\[[^\]]*\])/)[1] + ')');

// --- sanity: fail loudly rather than emit a half-empty seed -----------------
const expect = (cond, msg) => { if (!cond) throw new Error('sanity check failed: ' + msg); };
expect(EVENTS.length   === 24, `expected 24 events, got ${EVENTS.length}`);
expect(BOOKINGS.length === 13, `expected 13 bookings, got ${BOOKINGS.length}`);
expect(BUDGET.length   === 11, `expected 11 budget rows, got ${BUDGET.length}`);
expect(Object.keys(PACKING).length === 3, 'expected 3 packing groups');
expect(PEOPLE.length   === 3,  'expected 3 people');

// --- helpers ---------------------------------------------------------------
const q = v => (v === null || v === undefined || v === '') ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const n = v => (v === null || v === undefined || v === '') ? 'null' : Number(v);
const j = o => (o === null || o === undefined) ? 'null' : `'${JSON.stringify(o).replace(/'/g, "''")}'::jsonb`;

const TRIP_SLUG  = 'cyprus-dolomites-2026';
const TRIP_START = '2026-09-17';
const TRIP_END   = '2026-10-10';

/** Phase + where you sleep, both derived from the existing itinerary text. */
function phaseFor(iso) {
  if (iso <= '2026-09-21') return ['cyprus',  'Cyprus (Limassol or Paphos)'];
  if (iso <= '2026-09-25') return ['cortina', "Cortina d'Ampezzo"];
  if (iso <= '2026-09-28') return ['huts',    'Rifugio (Alta Via 1)'];
  if (iso <= '2026-10-04') return ['gardena', 'Ortisei, Val Gardena'];
  if (iso <= '2026-10-08') return ['garda',   'Riva del Garda'];
  return ['venice', 'Venice / Mestre'];
}

function eachDate(from, to) {
  const out = [];
  for (let d = new Date(from + 'T12:00:00'); d <= new Date(to + 'T12:00:00'); d.setDate(d.getDate() + 1)) {
    out.push(d.toISOString().slice(0, 10));
  }
  return out;
}

// --- build -----------------------------------------------------------------
const L = [];
L.push('-- ===========================================================================');
L.push('-- Shugon : seed of the existing Cyprus & Dolomites trip.');
L.push('--');
L.push('-- GENERATED by scripts/generate-seed.mjs from the arrays in index.html.');
L.push('-- Do not hand-edit: re-run the script instead.');
L.push('--');
L.push('-- Structured hike fields (distance_km, ascent_m, trailhead, parking,');
L.push('-- difficulty, map_url) are deliberately left NULL. Those numbers exist only');
L.push('-- inside prose notes ("~10km loop", "+900m") and pulling them out by pattern');
L.push('-- would quietly attach the wrong figure to the wrong walk. The prose is');
L.push('-- preserved verbatim in activities.notes for you to split up by hand.');
L.push('--');
L.push('-- Bookings are seeded UNSCHEDULED (day_id null). Only some name a date, and');
L.push('-- guessing the rest would invent facts. Drag them onto days in the app.');
L.push('-- ===========================================================================');
L.push('');
L.push('-- Every statement below stands alone: no temp tables, no session state,');
L.push('-- no explicit transaction. An earlier version staged the new trip id in a');
L.push('-- temp table, which works in psql but fails in the Supabase SQL editor —');
L.push('-- a temp table lives and dies with one session, and the editor does not');
L.push('-- guarantee that the whole script runs in a single one. Instead each');
L.push('-- statement looks the trip up by its slug, so order is the only');
L.push('-- requirement and re-running is always safe.');
L.push('');
L.push('-- Wipe any previous copy of this trip. Cascades to its days and activities.');
L.push(`delete from public.trips where slug = ${q(TRIP_SLUG)};`);
L.push('');
L.push('insert into public.trips (slug, title, subtitle, start_date, end_date, sort_order)');
L.push(`values (${q(TRIP_SLUG)}, ${q('Cyprus & the Dolomites')}, ${q('24 days · 3 friends · TLV → LCA → VCE → TLV')}, ${q(TRIP_START)}, ${q(TRIP_END)}, 0);`);
L.push('');

/** Every insert resolves the trip by slug, so no statement depends on another. */
const FROM_TRIP = `from public.trips where slug = ${q(TRIP_SLUG)}`;

// people
L.push('-- people');
PEOPLE.forEach((p, i) => {
  L.push(`insert into public.people (trip_id, name, sort_order) select id, ${q(p)}, ${i} ${FROM_TRIP};`);
});
L.push('');

// days
L.push('-- days: every date in the trip, so empty days still exist to drag onto');
const byDate = new Map(EVENTS.map(e => [e[0], e]));
for (const iso of eachDate(TRIP_START, TRIP_END)) {
  const ev = byDate.get(iso);
  const [phase, base] = phaseFor(iso);
  const holiday = ev && ev[2] === 'Holiday' ? ev[1] : null;
  L.push(`insert into public.days (trip_id, date, title, base_location, phase, holiday) select id, ${q(iso)}, ${q(ev ? ev[1] : null)}, ${q(base)}, ${q(phase)}, ${q(holiday)} ${FROM_TRIP};`);
}
L.push('');

// activities from events
L.push('-- one activity per existing calendar entry, notes preserved verbatim');
for (const [iso, title, cat, notes] of EVENTS) {
  L.push(`insert into public.activities (trip_id, day_id, sort_order, title, kind, notes)`);
  L.push(`  select t.id, d.id, 0, ${q(title)}, ${q(String(cat).toLowerCase())}, ${q(notes)}`);
  L.push(`  from public.trips t join public.days d on d.trip_id = t.id and d.date = ${q(iso)}`);
  L.push(`  where t.slug = ${q(TRIP_SLUG)};`);
}
L.push('');

// bookings -> unscheduled activities carrying booking json
L.push('-- bookings: unscheduled backlog, each carrying its booking payload');
BOOKINGS.forEach(([title, detail, due, url, linkLabel], i) => {
  const booking = { needed: true, status: 'todo', due: due || null, note: detail || null, url: url || null, linkLabel: linkLabel || null };
  L.push(`insert into public.activities (trip_id, day_id, sort_order, title, kind, notes, booking)`);
  L.push(`  select id, null, ${i}, ${q(title)}, 'booking', ${q(detail)}, ${j(booking)} ${FROM_TRIP};`);
});
L.push('');

// budget
L.push('-- budget');
BUDGET.forEach(([label, est, note], i) => {
  L.push(`insert into public.budget_items (trip_id, label, est_amount, note, sort_order) select id, ${q(label)}, ${n(est)}, ${q(note)}, ${i} ${FROM_TRIP};`);
});
L.push('');

// packing
L.push('-- packing');
let pi = 0;
for (const [group, items] of Object.entries(PACKING)) {
  for (const item of items) {
    L.push(`insert into public.packing_items (trip_id, group_name, label, sort_order) select id, ${q(group)}, ${q(item)}, ${pi++} ${FROM_TRIP};`);
  }
}
L.push('');

mkdirSync(join(root, 'supabase'), { recursive: true });
const outPath = join(root, 'supabase', '003_seed_cyprus_dolomites.sql');
writeFileSync(outPath, L.join('\n'), 'utf8');

console.log(`wrote ${outPath}`);
console.log(`  days:      ${eachDate(TRIP_START, TRIP_END).length}`);
console.log(`  events:    ${EVENTS.length}`);
console.log(`  bookings:  ${BOOKINGS.length} (unscheduled)`);
console.log(`  budget:    ${BUDGET.length}`);
console.log(`  packing:   ${pi}`);
console.log(`  people:    ${PEOPLE.length}`);
